version: '2'
services:
    mongo:
        image: mongo:latest
        ports:
            - "27017"
    addressbook:
        image: suttiruk046/microservices
        depends_on: 
            - mongo
        ports:
            - 8080:8080
        links:
            - mongo
